supabase_url = "https://<PROJECT_ID>.supabase.co"
supabase_api_key = "<SUPABASE_ANON_OR_SERVICE_ROLE_KEY>"
supabase_db_url = "postgresql://<USER>:<PASSWORD>@<HOST>:5432/<DB>"
download_dest_dir = "/absolute/path/for/cache_and_databases"
book_dir_relative = "books"
profile_db_path = "database/profiles.db"
recipe_db_filename = "recipes.db"
